---
- name: "Fail if OS/Architecture is not supported"
  fail:
    msg: "Installing bmon on {{ (ansible_os_family | lower) + '_' + (ansible_architecture | lower) }} is unsupported."
  when:
    - "(install_bmon_packages | default({}))[(ansible_os_family | lower) + '_' + (ansible_architecture | lower)] is not defined"
    - "bmon is defined"
  tags:
    - "bmon"
- name: "Install bmon"
  package:
    pkg: "{{ install_bmon_packages[(ansible_os_family | lower) + '_' + (ansible_architecture | lower)] }}"
    state: "present"
  when:
    - "bmon is defined"
  tags:
    - "bmon"
